# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "askshopai"
client_id = "bcb89a022769c843ce7d6a7cdebae8ec"
application_url = "https://ecomrag--development.gadget.app/api/shopify/install-or-render"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://ecomrag--development.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
dev_store_url = "jj2000-chatbot.myshopify.com"
