# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "032a5a85fe73f08421e275abf9b83afc"
name = "askshop.ai"
application_url = "https://ecomrag.gadget.app/api/shopify/install-or-render"
embedded = true

[build]
dev_store_url = "ecom-rag.myshopify.com"
include_config_on_deploy = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://ecomrag.gadget.app/api/connections/auth/shopify/callback"
]

[webhooks]
api_version = "2024-01"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://ecomrag.gadget.app/webhooks/customers_redact"
  customer_data_request_url = "https://ecomrag.gadget.app/webhooks/customer_data_request"
  shop_deletion_url = "https://ecomrag.gadget.app/webhooks/shop_redact"

[pos]
embedded = false
